
name: Test Runner

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        symfony-version:
          - 6.1.3
          - 5.4.11
          - 5.3.14

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ matrix.symfony-version }}-${{ hashFiles('**/composer.json') }}
      - name: symfony/framework-bundle:${{ matrix.symfony-version }}
      - uses: php-actions/composer@v6
        with:
          php_version: 8.1
          command: composer require "symfony/framework-bundle:${{ matrix.symfony-version }}" && composer install
      - name: run test
      - run: composer test
